export const CALENDAR_CONSTANTS = {
  CELL_SIZE: 50,
  TOTAL_WIDTH: 350, // 7 * CELL_SIZE
  MONTH_HEADER_HEIGHT: 50,
  WEEKDAY_HEADER_HEIGHT: 50,
  CELL_ROW_HEIGHT: 50, // Same as CELL_SIZE
  TOTAL_ROWS: 6, // Maximum 6 rows in a month
  TOTAL_HEIGHT: 400, // MONTH_HEADER_HEIGHT + WEEKDAY_HEADER_HEIGHT + (CELL_ROW_HEIGHT * TOTAL_ROWS)
} as const;
